//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mcvhoconline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory
    {
        public string id { get; set; }
        public string product_id { get; set; }
        public string user_id { get; set; }
        public int stock { get; set; }
        public string location { get; set; }
        public System.DateTime created_at { get; set; }
        public string created_by { get; set; }
        public System.DateTime updated_at { get; set; }
        public string updated_by { get; set; }
    
        public virtual product product { get; set; }
        public virtual user user { get; set; }
    }
}
