//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mcvhoconline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order()
        {
            this.discount_used_detail = new HashSet<discount_used_detail>();
            this.order_details = new HashSet<order_details>();
        }
    
        public string id { get; set; }
        public decimal total_amount { get; set; }
        public System.DateTime order_date { get; set; }
        public System.DateTime bill_date { get; set; }
        public string status { get; set; }
        public decimal ship_cost { get; set; }
        public string shipper_id { get; set; }
        public string user_id { get; set; }
        public string discount_id { get; set; }
        public string address_id { get; set; }
        public System.DateTime created_at { get; set; }
        public string created_by { get; set; }
        public System.DateTime updated_at { get; set; }
        public string updated_by { get; set; }
    
        public virtual address address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<discount_used_detail> discount_used_detail { get; set; }
        public virtual discount discount { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<order_details> order_details { get; set; }
        public virtual shipper shipper { get; set; }
        public virtual user user { get; set; }
    }
}
